### ISSUE TITLE
DataTables warning: table id=OcsTable - Invalid JSON response.

### ISSUE THREAD

**Issue by sram-z** [pluginsGLPI/ocsinventoryng#329]
Hi,

Plugin version: 2.0.1
GLPI version:  10.0.2

Tools > OCS Inventory NG > Inventory Import > Import or linka new computers.

Preview is disabled:
When I choose a computer and click on Import or link new computers nothing happend.

If I enable preview :

Information
DataTables warning: table id=OcsTable - Invalid JSON response. For more
information about this errror, please see http://datatables.net/tn/1

Thanks
Zoltan

**Comment by rogeriooliveira123** [comment]
Same problem here! It's a bug?

**Comment by TomBigJ** [comment]
Hi,

We've got the same error.
**_Information
DataTables warning: table id=OcsTable - Invalid JSON response. For more
information about this errror, please see http://datatables.net/tn/1_**

Our environnement is :
GLPI 10.0.3
Plugin 2.0.2

I tried many things (resintallation from sractch with only one ocs server and 1 rule) but we've always have the problem.

**Comment by Mask66** [comment]
Same here, GLPI 0.9.5 updated to 10.0.3, Plugin updated to 2.0.3.

php ocsng_fullsync.php --debug
        Thread #-1: import computers from server: 'OCS210'
        Thread #-1: 348 computer(s)
.Uncaught Exception Error: Call to a member function getOcsComputer() on null in /usr/local/www/glpi/plugins/ocsinventoryng/hook.php at line 1364

**Comment by Mask66** [comment]
From the php-errors.log, first is an import, second a "force full sync" on an existing computer.

[2022-11-11 21:49:12] glpiphplog.CRITICAL:   *** Uncaught Exception Error: Call to a member function getOcsComputer() on null in /usr/local/www/glpi/plugins/ocsinventoryng/hook.php at line 1364
  Backtrace :
  src/Plugin.php:1559                                plugin_ocsinventoryng_ruleCollectionPrepareInputDataForProcess()
  src/RuleCollection.php:1772                        Plugin::doOneHook()
  src/RuleCollection.php:1579                        RuleCollection->prepareInputDataForProcessWithPlugins()
  ...ins/ocsinventoryng/inc/ocsprocess.class.php:526 RuleCollection->processAllRules()
  ...ins/ocsinventoryng/inc/ocsprocess.class.php:482 PluginOcsinventoryngOcsProcess::importComputer()
  plugins/ocsinventoryng/front/ocsng.import.php:107  PluginOcsinventoryngOcsProcess::processComputer()

[2022-11-11 21:58:12] glpiphplog.CRITICAL:   *** Uncaught Exception Error: Call to a member function getOcsComputer() on null in /usr/local/www/glpi/plugins/ocsinventoryng/hook.php at line 1364
  Backtrace :
  src/Plugin.php:1559                                plugin_ocsinventoryng_ruleCollectionPrepareInputDataForProcess()
  src/RuleCollection.php:1772                        Plugin::doOneHook()
  src/RuleCollection.php:1579                        RuleCollection->prepareInputDataForProcessWithPlugins()
  ...ins/ocsinventoryng/inc/ocsprocess.class.php:928 RuleCollection->processAllRules()
  ...ns/ocsinventoryng/inc/ocsprocess.class.php:1798 PluginOcsinventoryngOcsProcess::synchronizeComputer()
  src/MassiveAction.php:1404                         PluginOcsinventoryngOcsProcess::processMassiveActionsForOneItemtype()
  src/MassiveAction.php:1382                         MassiveAction->processForSeveralItemtypes()
  front/massiveaction.php:59                         MassiveAction->process()

**Comment by tsmr** [comment]
Please try with master version ? https://github.com/pluginsGLPI/ocsinventoryng/archive/refs/heads/master.zip

**Comment by tsmr** [comment]
fixed in 2.0.4

**Comment by mcfx78** [comment]
Hi all, 

i've install glpi 10.0.6 and OCSinventory 2.0.4 but i still have the same problem.
Can you help me?

**Comment by R0dS3rling** [comment]
Hi,

Same problem with glpi 10.0.11 and ocsserver 2.12.1
Can you please help, we're completly blocked.

Thanks in advance.

**Comment by rafaelrsilver** [comment]
hi people, 

same problem here, [GLPI 10.0.12], Plugin 2.0.4.

Did anyone manage to solve it?

**Comment by ALJBRA** [comment]
In my case i just add a private $dbname; above private $db line 40 in file ocsdbclient.class

this is used in constructor

    public function __construct($id, $dbhost, $dbuser, $dbpassword, $dbdefault)
    {
        parent::__construct($id);
        $this->db = new PluginOcsinventoryngDBocs($dbhost, $dbuser, $dbpassword, $dbdefault);
        $this->dbname = $dbdefault;
    }


    /**
     * @var DBmysql
     */
  40  private $db;
  41  private $dbname;
