### ISSUE TITLE
Plugin not compatible with ocs  2.0.5-1.3

### ISSUE THREAD

**Issue by hdep** [pluginsGLPI/ocsinventoryng#52]
Hello,

running the lastest plugin 1.2.3 on glpi 9.1  I got a sql error when trying to import computers : 

```
2016-11-02 15:54:37 [2@server]
  *** MySQL query error:
  SQL: SELECT * FROM `cpus` WHERE `HARDWARE_ID` IN (305)
  Error: Table 'ocs.cpus' doesn't exist
  Backtrace :
  ...ns/ocsinventoryng/inc/ocsdbclient.class.php:231
  ...ns/ocsinventoryng/inc/ocsdbclient.class.php:554 PluginOcsinventoryngOcsDbClient->getComputerSections()
  plugins/ocsinventoryng/inc/ocsclient.class.php:317 PluginOcsinventoryngOcsDbClient->getComputers()
  ...ins/ocsinventoryng/inc/ocsserver.class.php:2556 PluginOcsinventoryngOcsClient->getComputer()
  ...ins/ocsinventoryng/inc/ocsserver.class.php:2257 PluginOcsinventoryngOcsServer::updateComputer()
  ...ins/ocsinventoryng/inc/ocsserver.class.php:1817 PluginOcsinventoryngOcsServer::importComputer()
  plugins/ocsinventoryng/front/ocsng.import.php:73   PluginOcsinventoryngOcsServer::processComputer()
```

Looking at the database of ocs, I don't have any cpus table. 

My ocs server is coming from the debian repository  (hence the database schema too) : 
`ii  ocsinventory-server            2.0.5-1.3                   all          Hardware and software inventory tool (Communication Server)`

Any idea ? 

Thank you.

**Comment by tsmr** [comment]
i have pushed a correction. Can you try to add this correction into you inc\ocsserver.class.php ?

**Comment by hdep** [comment]
Hello,

with your fix, import is working (I don't get error from SQL), but I still don't have the CPUs information in GLPI.
Is that expected behaviour ? 

Regards,

**Comment by tsmr** [comment]
Normal, you must upgrade your OCS server installation :P

**Comment by hdep** [comment]
I was waiting for this answer :)

Thank you anyway.

**Comment by gitdevmod** [comment]
Hi,

Just to be sure, what is the minimal OCS Inventory NG Server version required for the plugin ?
Thanks
